=== ati72/d2ovj9_XMLGyak/XMLTaskD2ovj9/XSDD2ovj9.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="adatok">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tulajdonos" type="tulaj_type" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="kiado" type="kiado_type" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="zenekar" type="zenekar_type" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="zenesz" type="zenesz_type" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="hangszer" type="hangszer_type" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="hangszerismeret" type="hangszerismeret_type" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
		<!-- Kulcsok (Kulcs és rámutató idegen kulcs párokban)-->
		<!-- Tulaj -->
		<xs:key name="tulaj_ID">
            <xs:selector xpath=".//tulajdonos" />
            <xs:field xpath="@ID" />
        </xs:key>
        <xs:keyref name="tulaj_ID_ref" refer="tulaj_ID">
            <xs:selector xpath=".//kiado" />
            <xs:field xpath="@tulaj_ID" />
        </xs:keyref>
		<!-- Kiado -->
		<xs:key name="kiado_ID">
            <xs:selector xpath=".//kiado" />
            <xs:field xpath="@ID" />
        </xs:key>
        <xs:keyref name="kiado_ID_ref" refer="kiado_ID">
            <xs:selector xpath=".//zenekar" />
            <xs:field xpath="@kiado_ID" />
        </xs:keyref>
		<!-- Zenekar -->
		<xs:key name="zenekar_ID">
            <xs:selector xpath=".//zenekar" />
            <xs:field xpath="@ID" />
        </xs:key>
        <xs:keyref name="zenekar_ID_ref" refer="zenekar_ID">
            <xs:selector xpath=".//zenesz" />
            <xs:field xpath="@zenekar_ID" />
        </xs:keyref>
		<!-- Zenesz -->
		<xs:key name="zenesz_ID">
            <xs:selector xpath=".//zenesz" />
            <xs:field xpath="@ID" />
        </xs:key>
        <xs:keyref name="zenesz_ID_ref" refer="zenesz_ID">
            <xs:selector xpath=".//hangszerismeret" />
            <xs:field xpath="@zenesz_ID" />
        </xs:keyref>
		<!-- Hangszer -->
		<xs:key name="hangszer_ID">
            <xs:selector xpath=".//hangszer" />
            <xs:field xpath="@ID" />
        </xs:key>
        <xs:keyref name="hangszer_ID_ref" refer="hangszer_ID">
            <xs:selector xpath=".//hangszerismeret" />
            <xs:field xpath="@hangszer_ID" />
        </xs:keyref>
		<!-- 1:1 Kapcs -->
		<xs:unique name="egy_tulaj">
            <xs:selector xpath=".//kiado"></xs:selector>
            <xs:field xpath="@tulaj_ID"></xs:field>
        </xs:unique>

	</xs:element>
	
	
	<!-- Sajat tipusok -->
	<!-- Tulaj -->
	<xs:complexType name="tulaj_type">
		<xs:sequence>
			<xs:element name="vezeteknev" type="xs:string"/>
			<xs:element name="keresztnev" type="xs:string"/>
			<xs:element name="telefonszam" type="xs:string"/>
			<xs:element name="email" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Kiado -->
	<xs:complexType name="kiado_type">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="telephely" type="xs:string"/>
			<xs:element name="email" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string" use="required"/>
		<xs:attribute name="tulaj_ID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Zenekar -->
	<xs:complexType name="zenekar_type">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="alakult" type="xs:string"/>
			<xs:element name="mufaj" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string" use="required"/>
		<xs:attribute name="kiado_ID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Zenesz -->
	<xs:complexType name="zenesz_type">
		<xs:sequence>
			<xs:element name="vezeteknev" type="xs:string"/>
			<xs:element name="keresztnev" type="xs:string"/>
			<xs:element name="szuletett" type="xs:string"/>
			<xs:element name="nem" type="nem_type"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string" use="required"/>
		<xs:attribute name="zenekar_ID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Hangszer -->
	<xs:complexType name="hangszer_type">
		<xs:sequence>
			<xs:element name="gyarto" type="xs:string"/>
			<xs:element name="tipus" type="xs:string"/>
			<xs:element name="osztaly" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Hangszerismeret -->
	<xs:complexType name="hangszerismeret_type">
		<xs:sequence>
			<xs:element name="ideje" type="xs:string"/>
			<xs:element name="szint" type="szint_type"/>
		</xs:sequence>
		<xs:attribute name="hangszer_ID" type="xs:string" use="required"/>
		<xs:attribute name="zenesz_ID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Egyszeru tipusok a tobberteku egyedekhez -->
	<xs:simpleType name="szint_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Virtuóz"/>
            <xs:enumeration value="Tapasztalt"/>
            <xs:enumeration value="Alibi"/>
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="nem_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="F"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ati72/d2ovj9_XMLGyak/XMLTaskD2ovj9/XMLD2ovj9.xml
<?xml version="1.0" encoding="UTF-8"?>

<adatok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDD2ovj9.xsd">
	<!-- Tulajok -->
	<tulajdonos tulaj_ID="tul-01">
		<vezeteknev>Major</vezeteknev>
		<keresztnev>Anna</keresztnev>
		<telefonszam>06201234567</telefonszam>
		<email>majoranna@gmail.com</email>
	</tulajdonos>
	<tulajdonos tulaj_ID="tul-02">
		<vezeteknev>Feles</vezeteknev>
		<keresztnev>Elek</keresztnev>
		<telefonszam>06309877654</telefonszam>
		<email>feles@elek.hu</email>
	</tulajdonos>
	<tulajdonos tulaj_ID="tul-03">
		<vezeteknev>Ultra</vezeteknev>
		<keresztnev>Viola</keresztnev>
		<telefonszam>06709844565</telefonszam>
		<email>ultrav@gmail.com</email>
	</tulajdonos>
	<!-- Kiadók -->
	<kiado kiado_ID="kia-01" tulaj_ID="tul-01">
		<nev>Major Records</nev>
		<telephely>Eger, Széchenyi út 20</telephely>
		<email>majorrecords@gmail.com</email>
	</kiado>
	<kiado kiado_ID="kia-02" tulaj_ID="tul-02">
		<nev>Feles Music</nev>
		<telephely>Budapest, Rákóczi út 32</telephely>
		<email>feles_music@gmail.com</email>
	</kiado>
	<kiado kiado_ID="kia-03" tulaj_ID="tul-03">
		<nev>Ultra Sound</nev>
		<telephely>Székesfehérvár, Kárpát út 13</telephely>
		<email>ultrasound@hotmail.com</email>
	</kiado>
	<!-- Zenekarok -->
	<zenekar zenekar_ID="zk-01" kiado_ID='kia-01'>
		<nev>Admin</nev>
		<alakult>1999</alakult>
		<mufaj>Rock</mufaj>
	</zenekar>
	<zenekar zenekar_ID="zk-02" kiado_ID='kia-02'>
		<nev>Quake</nev>
		<alakult>2009</alakult>
		<mufaj>Punk</mufaj>
	</zenekar>
	<zenekar zenekar_ID="zk-03" kiado_ID='kia-03'>
		<nev>Algoritmus</nev>
		<alakult>1986</alakult>
		<mufaj>Alternatív</mufaj>
	</zenekar>
	<!-- Zeneszek -->
	<zenesz zenesz_ID="zen-01" zenekar_ID="zk-01">
		<vezeteknev>Para</vezeteknev>
		<keresztnev>Zita</keresztnev>
		<szuletett>1980</szuletett>
	</zenesz>
	<zenesz zenesz_ID="zen-02" zenekar_ID="zk-02">
		<vezeteknev>Git</vezeteknev>
		<keresztnev>Áron</keresztnev>
		<szuletett>1990</szuletett>
	</zenesz>
	<zenesz zenesz_ID="zen-03" zenekar_ID="zk-03">
		<vezeteknev>Techno</vezeteknev>
		<keresztnev>Kolos</keresztnev>
		<szuletett>1969</szuletett>
	</zenesz>
	<!-- Hangszerek -->
	<hangszer hangszer_ID="hsz-01">
		<gyarto>Roland</gyarto>
		<tipus>FP-30X</tipus>
		<osztaly>Billentyűs</osztaly>
	</hangszer>
	<hangszer hangszer_ID="hsz-02">
		<gyarto>Fender</gyarto>
		<tipus>Stratocaster</tipus>
		<osztaly>Gitár</osztaly>
	</hangszer>
	<hangszer hangszer_ID="hsz-03">
		<gyarto>Pearl</gyarto>
		<tipus>Roadshow</tipus>
		<osztaly>Dob</osztaly>
	</hangszer>
	<hangszerismeret hangszer_ID="hsz-01" zenesz_ID="zen-01">
		<ideje>5</ideje>
	</hangszerismeret>
	<hangszerismeret hangszer_ID="hsz-02" zenesz_ID="zen-02">
		<ideje>3</ideje>
	</hangszerismeret>
	<hangszerismeret hangszer_ID="hsz-03" zenesz_ID="zen-03">
		<ideje>20</ideje>
	</hangszerismeret>
</adatok>
